"""
PostgreSQL database service for OrgSight 2.0.

Stores the final processed dataset after the pipeline completes, plus scenarios
that branch off the baseline for org modelling (drag-and-drop moves, edits,
soft-deletes, adds).

All data lives in OrgSight_db only (see pg_adapter.REQUIRED_DATABASE).
"""

import json
import logging
import os
import sys
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

from services.pg_adapter import IntegrityError, PgConnection, _connect, _connect_ro, run_with_migration_lock

logger = logging.getLogger(__name__)

_ID_PK = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"


def init_db() -> None:
    """Create tables if they don't already exist. Safe to call on every startup."""
    with _connect() as conn:
        c = conn.cursor()

        c.execute(
            f"""
            CREATE TABLE IF NOT EXISTS datasets (
                id            {_ID_PK},
                name          TEXT NOT NULL,
                username      TEXT NOT NULL,
                upload_time   TEXT NOT NULL,
                emp_col       TEXT NOT NULL,
                mgr_col       TEXT NOT NULL,
                fte_col       TEXT,
                flc_col       TEXT,
                job_title_col TEXT,
                country_col   TEXT,
                row_count     INTEGER NOT NULL DEFAULT 0
            )
            """
        )

        c.execute(
            f"""
            CREATE TABLE IF NOT EXISTS baseline_records (
                id          {_ID_PK},
                dataset_id  INTEGER NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
                emp_id      TEXT NOT NULL,
                mgr_id      TEXT,
                level       INTEGER,
                fte         DOUBLE PRECISION,
                flc         DOUBLE PRECISION,
                data_json   TEXT NOT NULL
            )
            """
        )
        c.execute("CREATE INDEX IF NOT EXISTS idx_baseline_dataset ON baseline_records(dataset_id)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_baseline_emp ON baseline_records(dataset_id, emp_id)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_baseline_mgr ON baseline_records(dataset_id, mgr_id)")

        c.execute(
            f"""
            CREATE TABLE IF NOT EXISTS scenarios (
                id           {_ID_PK},
                dataset_id   INTEGER NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
                name         TEXT NOT NULL,
                description  TEXT,
                created_at   TEXT NOT NULL,
                updated_at   TEXT NOT NULL,
                is_promoted  INTEGER NOT NULL DEFAULT 0
            )
            """
        )
        c.execute("CREATE INDEX IF NOT EXISTS idx_scenarios_dataset ON scenarios(dataset_id)")

        c.execute(
            f"""
            CREATE TABLE IF NOT EXISTS scenario_records (
                id                 {_ID_PK},
                scenario_id        INTEGER NOT NULL REFERENCES scenarios(id) ON DELETE CASCADE,
                emp_id             TEXT NOT NULL,
                mgr_id             TEXT,
                level              INTEGER,
                fte                DOUBLE PRECISION,
                flc                DOUBLE PRECISION,
                is_flagged_removed INTEGER NOT NULL DEFAULT 0,
                is_added           INTEGER NOT NULL DEFAULT 0,
                data_json          TEXT NOT NULL,
                UNIQUE (scenario_id, emp_id)
            )
            """
        )
        c.execute("CREATE INDEX IF NOT EXISTS idx_scenario_records_sid ON scenario_records(scenario_id)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_scenario_records_mgr ON scenario_records(scenario_id, mgr_id)")

        c.execute(
            f"""
            CREATE TABLE IF NOT EXISTS change_log (
                id           {_ID_PK},
                scenario_id  INTEGER NOT NULL REFERENCES scenarios(id) ON DELETE CASCADE,
                action       TEXT NOT NULL,
                emp_id       TEXT,
                old_mgr_id   TEXT,
                new_mgr_id   TEXT,
                field        TEXT,
                old_value    TEXT,
                new_value    TEXT,
                timestamp    TEXT NOT NULL,
                username     TEXT
            )
            """
        )
        c.execute("CREATE INDEX IF NOT EXISTS idx_change_log_sid ON change_log(scenario_id)")

        c.execute(
            f"""
            CREATE TABLE IF NOT EXISTS users (
                id                   {_ID_PK},
                username             TEXT NOT NULL UNIQUE,
                display_name         TEXT,
                password_hash        TEXT NOT NULL,
                role                 TEXT NOT NULL DEFAULT 'member',
                is_active            INTEGER NOT NULL DEFAULT 1,
                must_change_password INTEGER NOT NULL DEFAULT 1,
                created_at           TEXT NOT NULL,
                updated_at           TEXT NOT NULL
            )
            """
        )
        c.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON users(username)")

        c.execute(
            f"""
            CREATE TABLE IF NOT EXISTS refresh_tokens (
                id          {_ID_PK},
                user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                token_hash  TEXT NOT NULL UNIQUE,
                expires_at  TEXT NOT NULL,
                created_at  TEXT NOT NULL,
                revoked_at  TEXT
            )
            """
        )
        c.execute("CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens(user_id)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash ON refresh_tokens(token_hash)")

        c.execute(
            """
            CREATE TABLE IF NOT EXISTS schema_version (
                version INTEGER NOT NULL DEFAULT 0
            )
            """
        )
        if c.execute("SELECT COUNT(*) AS n FROM schema_version").fetchone()["n"] == 0:
            c.execute("INSERT INTO schema_version (version) VALUES (0)")

        conn.commit()

    _seed_admin()
    _migrate_legacy_users()
    _run_migrations()


# ---------------------------------------------------------------------------
# Admin seeding + legacy user migration
# ---------------------------------------------------------------------------

def _seed_admin() -> None:
    """Create the first admin user from environment variables.

    Requires SEED_ADMIN_USERNAME and SEED_ADMIN_PASSWORD to both be set.
    If an admin already exists, this is a no-op.
    If neither env var is set and no admin exists, exits with a clear error.
    SEED_ADMIN_PASSWORD is never logged.
    """
    from argon2 import PasswordHasher

    with _connect_ro() as conn:
        admin_exists = conn.execute(
            "SELECT COUNT(*) AS n FROM users WHERE role = 'admin'"
        ).fetchone()["n"]
        if admin_exists:
            return

    seed_username = os.environ.get("SEED_ADMIN_USERNAME")
    seed_password = os.environ.get("SEED_ADMIN_PASSWORD")

    if not seed_username or not seed_password:
        logger.critical(
            "No admin user exists and SEED_ADMIN_USERNAME / SEED_ADMIN_PASSWORD "
            "environment variables are not both set. Cannot start without an admin. "
            "Set both env vars and restart."
        )
        sys.exit(1)

    ph = PasswordHasher()
    now = datetime.utcnow().isoformat()

    with _connect() as conn:
        existing = conn.execute(
            "SELECT id FROM users WHERE username = ?", (seed_username,)
        ).fetchone()
        if existing:
            conn.execute(
                "UPDATE users SET role = 'admin', updated_at = ? WHERE username = ?",
                (now, seed_username),
            )
        else:
            conn.execute(
                """
                INSERT INTO users
                    (username, display_name, password_hash, role, is_active,
                     must_change_password, created_at, updated_at)
                VALUES (?, ?, ?, 'admin', 1, 1, ?, ?)
                """,
                (seed_username, seed_username, ph.hash(seed_password), now, now),
            )
        conn.commit()
    logger.info("Seeded admin user: %s", seed_username)


def _migrate_legacy_users() -> None:
    """Migrate the hardcoded VALID_USERS dict into the users table.

    Existing usernames are skipped. All migrated users get
    must_change_password=true so they set a real password on first login.
    """
    from argon2 import PasswordHasher

    LEGACY_USERS = {
        "aishwaryajain": "shwryjn",
        "dmirakhur": "dmrkhr",
        "sparashar": "sprshr",
        "abhishek.singh": "bhshksngh",
        "varun.singh": "vrnsngh",
        "ankit.arora": "nktrr",
        "jnad": "jytsnd>",
        "sroutray": "srtry>",
        "a.goel": "dtygl",
        "ppruthi": "pprth",
        "arao": "bhnvr",
        "rraj": "rhlrj",
        "ashish.mehta": "shshmht",
        "hmakkar": "hmkkr",
        "gbhatia": "gbht",
    }

    ph = PasswordHasher()
    now = datetime.utcnow().isoformat()
    migrated = 0

    with _connect() as conn:
        for username, password in LEGACY_USERS.items():
            existing = conn.execute(
                "SELECT id FROM users WHERE username = ?", (username,)
            ).fetchone()
            if existing:
                continue
            conn.execute(
                """
                INSERT INTO users
                    (username, display_name, password_hash, role, is_active,
                     must_change_password, created_at, updated_at)
                VALUES (?, ?, ?, 'member', 1, 1, ?, ?)
                """,
                (username, username, ph.hash(password), now, now),
            )
            migrated += 1
        conn.commit()

    if migrated:
        logger.info("Migrated %d legacy users into users table", migrated)


# ---------------------------------------------------------------------------
# Schema migrations (Phase 2+)
# ---------------------------------------------------------------------------

def _migrate_v1(conn: PgConnection) -> None:
    """v1: projects + project_assignments + audit_log tables."""
    c = conn.cursor()

    c.execute(
        f"""
        CREATE TABLE IF NOT EXISTS projects (
            id          {_ID_PK},
            name        TEXT NOT NULL,
            description TEXT,
            deadline    TEXT,
            status      TEXT NOT NULL DEFAULT 'active',
            created_by  INTEGER NOT NULL REFERENCES users(id),
            created_at  TEXT NOT NULL,
            updated_at  TEXT NOT NULL
        )
        """
    )

    c.execute(
        f"""
        CREATE TABLE IF NOT EXISTS project_assignments (
            id          {_ID_PK},
            project_id  INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            user_id     INTEGER NOT NULL REFERENCES users(id),
            role        TEXT NOT NULL DEFAULT 'member',
            assigned_at TEXT NOT NULL,
            assigned_by INTEGER NOT NULL REFERENCES users(id),
            UNIQUE (project_id, user_id)
        )
        """
    )
    c.execute("CREATE INDEX IF NOT EXISTS idx_pa_project ON project_assignments(project_id)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_pa_user ON project_assignments(user_id)")

    c.execute(
        f"""
        CREATE TABLE IF NOT EXISTS audit_log (
            id            {_ID_PK},
            user_id       INTEGER,
            action        TEXT NOT NULL,
            resource_type TEXT,
            resource_id   INTEGER,
            details_json  TEXT,
            ip_address    TEXT,
            created_at    TEXT NOT NULL
        )
        """
    )
    c.execute("CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log(created_at)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON audit_log(user_id)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log(action)")


def _migrate_v2(conn: PgConnection) -> None:
    """v2: Add project_id to datasets + backfill Legacy project."""
    c = conn.cursor()

    cols = [
        row["column_name"]
        for row in c.execute(
            """
            SELECT column_name FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'datasets'
            """
        ).fetchall()
    ]
    if "project_id" not in cols:
        c.execute("ALTER TABLE datasets ADD COLUMN project_id INTEGER REFERENCES projects(id)")

    now = datetime.utcnow().isoformat()
    admin = c.execute(
        "SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1"
    ).fetchone()
    admin_id = admin["id"] if admin else 1

    existing_legacy = c.execute(
        "SELECT id FROM projects WHERE name = 'Legacy' LIMIT 1"
    ).fetchone()

    if existing_legacy:
        legacy_project_id = existing_legacy["id"]
    else:
        c.execute(
            """
            INSERT INTO projects (name, description, status, created_by, created_at, updated_at)
            VALUES ('Legacy', 'Auto-created project for pre-existing datasets', 'active', ?, ?, ?)
            """,
            (admin_id, now, now),
        )
        legacy_project_id = c.lastrowid

    orphan_count = c.execute(
        "SELECT COUNT(*) AS n FROM datasets WHERE project_id IS NULL"
    ).fetchone()["n"]
    if orphan_count > 0:
        c.execute(
            "UPDATE datasets SET project_id = ? WHERE project_id IS NULL",
            (legacy_project_id,),
        )

    active_users = c.execute("SELECT id FROM users WHERE is_active = 1").fetchall()
    for user_row in active_users:
        c.execute(
            """
            INSERT INTO project_assignments (project_id, user_id, role, assigned_at, assigned_by)
            VALUES (?, ?, 'member', ?, ?)
            ON CONFLICT (project_id, user_id) DO NOTHING
            """,
            (legacy_project_id, user_row["id"], now, admin_id),
        )

    if orphan_count > 0:
        logger.info(
            "Legacy project (id=%d), %d orphaned datasets backfilled, %d users assigned",
            legacy_project_id, orphan_count, len(active_users),
        )
    else:
        logger.info(
            "Legacy project ensured (id=%d), %d users assigned",
            legacy_project_id, len(active_users),
        )


def _migrate_v3(conn: PgConnection) -> None:
    """v3: project_locks table for soft-locking."""
    c = conn.cursor()
    c.execute(
        """
        CREATE TABLE IF NOT EXISTS project_locks (
            project_id     INTEGER PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
            user_id        INTEGER NOT NULL REFERENCES users(id),
            username       TEXT NOT NULL,
            acquired_at    TEXT NOT NULL,
            last_heartbeat TEXT NOT NULL
        )
        """
    )
    c.execute("CREATE INDEX IF NOT EXISTS idx_locks_heartbeat ON project_locks(last_heartbeat)")


def _migrate_v4(conn: PgConnection) -> None:
    """v4: dataset_locks table for dataset-level edit locking."""
    c = conn.cursor()
    c.execute(
        """
        CREATE TABLE IF NOT EXISTS dataset_locks (
            dataset_id     INTEGER PRIMARY KEY REFERENCES datasets(id) ON DELETE CASCADE,
            project_id     INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            user_id        INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            username       TEXT NOT NULL,
            acquired_at    TEXT NOT NULL,
            last_heartbeat TEXT NOT NULL
        )
        """
    )
    c.execute("CREATE INDEX IF NOT EXISTS idx_dslocks_heartbeat ON dataset_locks(last_heartbeat)")


def _migrate_v5(conn: PgConnection) -> None:
    """v5: dataset_user_views table -- tracks per-user 'last seen' timestamps."""
    c = conn.cursor()
    c.execute(
        f"""
        CREATE TABLE IF NOT EXISTS dataset_user_views (
            id         {_ID_PK},
            dataset_id INTEGER NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
            user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            last_seen  TEXT NOT NULL,
            UNIQUE (dataset_id, user_id)
        )
        """
    )
    c.execute("CREATE INDEX IF NOT EXISTS idx_duv_dataset ON dataset_user_views(dataset_id)")
    c.execute("CREATE INDEX IF NOT EXISTS idx_duv_user ON dataset_user_views(user_id)")

def _migrate_v6(conn: PgConnection) -> None:
    """v6: rate cards + scenario rate-card settings."""
    c = conn.cursor()

    c.execute(
        f"""
        CREATE TABLE IF NOT EXISTS rate_card_definitions (
            id                 {_ID_PK},
            dataset_id         INTEGER NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
            name               TEXT NOT NULL,
            property_cols_json TEXT NOT NULL,
            cost_col           TEXT NOT NULL,
            min_sample         INTEGER NOT NULL DEFAULT 3,
            created_at         TEXT NOT NULL,
            created_by         TEXT
        )
        """
    )
    c.execute("CREATE INDEX IF NOT EXISTS idx_rate_cards_dataset ON rate_card_definitions(dataset_id)")

    c.execute(
        f"""
        CREATE TABLE IF NOT EXISTS rate_card_rows (
            id                 {_ID_PK},
            rate_card_id       INTEGER NOT NULL REFERENCES rate_card_definitions(id) ON DELETE CASCADE,
            composite_key      TEXT NOT NULL,
            p25                DOUBLE PRECISION,
            p50                DOUBLE PRECISION,
            p75                DOUBLE PRECISION,
            avg_cost           DOUBLE PRECISION,
            sample_count       INTEGER NOT NULL DEFAULT 0,
            is_manual_override INTEGER NOT NULL DEFAULT 0,
            UNIQUE (rate_card_id, composite_key)
        )
        """
    )
    c.execute("CREATE INDEX IF NOT EXISTS idx_rate_card_rows_rc ON rate_card_rows(rate_card_id)")

    cols = [
        row["column_name"]
        for row in c.execute(
            """
            SELECT column_name FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'scenarios'
            """
        ).fetchall()
    ]
    if "rate_card_id" not in cols:
        c.execute(
            "ALTER TABLE scenarios ADD COLUMN rate_card_id INTEGER "
            "REFERENCES rate_card_definitions(id) ON DELETE SET NULL"
        )
    if "rate_card_quartile" not in cols:
        c.execute(
            "ALTER TABLE scenarios ADD COLUMN rate_card_quartile TEXT NOT NULL DEFAULT 'p50'"
        )



_MIGRATIONS = [
    (1, "projects + assignments + audit_log tables", _migrate_v1),
    (2, "project_id on datasets + Legacy project backfill", _migrate_v2),
    (3, "project_locks table", _migrate_v3),
    (4, "dataset_locks table", _migrate_v4),
    (5, "dataset_user_views table", _migrate_v5),
    (6, "rate cards + scenario rate-card settings", _migrate_v6),
]


def _run_migrations() -> None:
    """Run pending schema migrations in order (serialized via pg_advisory_lock)."""
    with _connect() as conn:
        def _apply(conn: PgConnection) -> None:
            current = conn.execute("SELECT version FROM schema_version").fetchone()["version"]
            for version, description, fn in _MIGRATIONS:
                if version > current:
                    logger.info("Running migration v%d: %s", version, description)
                    fn(conn)
                    conn.execute("UPDATE schema_version SET version = ?", (version,))
                    conn.commit()
                    logger.info("Migration v%d complete", version)

        run_with_migration_lock(conn, _apply)


# ---------------------------------------------------------------------------
# User queries (used by auth dependencies)
# ---------------------------------------------------------------------------

def get_user_by_id(user_id: int) -> Optional[Dict[str, Any]]:
    with _connect_ro() as conn:
        row = conn.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()
        return dict(row) if row else None


def get_user_by_username(username: str) -> Optional[Dict[str, Any]]:
    with _connect_ro() as conn:
        row = conn.execute(
            "SELECT * FROM users WHERE username = ?", (username,)
        ).fetchone()
        return dict(row) if row else None


def create_user(
    username: str,
    password_hash: str,
    display_name: Optional[str] = None,
    role: str = "member",
) -> int:
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()
        c.execute(
            """
            INSERT INTO users
                (username, display_name, password_hash, role, is_active,
                 must_change_password, created_at, updated_at)
            VALUES (?, ?, ?, ?, 1, 1, ?, ?)
            """,
            (username, display_name or username, password_hash, role, now, now),
        )
        conn.commit()
        return c.lastrowid


def update_user_password(user_id: int, password_hash: str, clear_must_change: bool = True) -> None:
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        if clear_must_change:
            conn.execute(
                "UPDATE users SET password_hash = ?, must_change_password = 0, updated_at = ? WHERE id = ?",
                (password_hash, now, user_id),
            )
        else:
            conn.execute(
                "UPDATE users SET password_hash = ?, updated_at = ? WHERE id = ?",
                (password_hash, now, user_id),
            )
        conn.commit()


# ---------------------------------------------------------------------------
# Refresh token persistence
# ---------------------------------------------------------------------------

def store_refresh_token(user_id: int, token_hash: str, expires_at: str) -> int:
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()
        c.execute(
            """
            INSERT INTO refresh_tokens (user_id, token_hash, expires_at, created_at)
            VALUES (?, ?, ?, ?)
            """,
            (user_id, token_hash, expires_at, now),
        )
        conn.commit()
        return c.lastrowid


def get_refresh_token(token_hash: str) -> Optional[Dict[str, Any]]:
    with _connect_ro() as conn:
        row = conn.execute(
            "SELECT * FROM refresh_tokens WHERE token_hash = ? AND revoked_at IS NULL",
            (token_hash,),
        ).fetchone()
        return dict(row) if row else None


def revoke_refresh_token(token_hash: str) -> None:
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        conn.execute(
            "UPDATE refresh_tokens SET revoked_at = ? WHERE token_hash = ?",
            (now, token_hash),
        )
        conn.commit()


def revoke_all_user_tokens(user_id: int) -> None:
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        conn.execute(
            "UPDATE refresh_tokens SET revoked_at = ? WHERE user_id = ? AND revoked_at IS NULL",
            (now, user_id),
        )
        conn.commit()


# ---------------------------------------------------------------------------
# Dataset + baseline persistence
# ---------------------------------------------------------------------------

def save_baseline(
    name: str,
    username: str,
    records: List[Dict[str, Any]],
    emp_col: str,
    mgr_col: str,
    fte_col: Optional[str] = None,
    flc_col: Optional[str] = None,
    job_title_col: Optional[str] = None,
    country_col: Optional[str] = None,
    project_id: Optional[int] = None,
) -> int:
    """Persist a fully-processed dataset as the baseline and create a default
    'Baseline' scenario that mirrors it. Returns the new dataset_id."""
    now = datetime.utcnow().isoformat()

    with _connect() as conn:
        c = conn.cursor()
        c.execute(
            """
            INSERT INTO datasets
                (name, username, upload_time, emp_col, mgr_col, fte_col, flc_col,
                 job_title_col, country_col, row_count, project_id)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (name, username, now, emp_col, mgr_col, fte_col, flc_col,
             job_title_col, country_col, len(records), project_id),
        )
        dataset_id = c.lastrowid

        rows = []
        for row in records:
            emp_id = _to_str(row.get(emp_col))
            mgr_id = _to_str(row.get(mgr_col))
            level = _to_int(row.get("Level"))
            fte = _to_float(row.get(fte_col)) if fte_col else None
            flc = _to_float(row.get(flc_col)) if flc_col else None
            rows.append((dataset_id, emp_id, mgr_id, level, fte, flc, json.dumps(row, default=str)))

        c.executemany(
            """
            INSERT INTO baseline_records
                (dataset_id, emp_id, mgr_id, level, fte, flc, data_json)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            rows,
        )

        # Auto-create a default scenario that mirrors the baseline
        c.execute(
            """
            INSERT INTO scenarios (dataset_id, name, description, created_at, updated_at, is_promoted)
            VALUES (?, ?, ?, ?, ?, 0)
            """,
            (dataset_id, "Baseline", "Default working scenario (mirrors baseline)", now, now),
        )
        scenario_id = c.lastrowid

        scenario_rows = []
        for row in records:
            emp_id = _to_str(row.get(emp_col))
            mgr_id = _to_str(row.get(mgr_col))
            level = _to_int(row.get("Level"))
            fte = _to_float(row.get(fte_col)) if fte_col else None
            flc = _to_float(row.get(flc_col)) if flc_col else None
            scenario_rows.append(
                (scenario_id, emp_id, mgr_id, level, fte, flc, 0, 0, json.dumps(row, default=str))
            )

        c.executemany(
            """
            INSERT INTO scenario_records
                (scenario_id, emp_id, mgr_id, level, fte, flc,
                 is_flagged_removed, is_added, data_json)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            scenario_rows,
        )

        conn.commit()
        return dataset_id


def list_datasets(username: Optional[str] = None, project_id: Optional[int] = None) -> List[Dict[str, Any]]:
    with _connect_ro() as conn:
        clauses, params = [], []
        if username:
            clauses.append("username = ?")
            params.append(username)
        if project_id is not None:
            clauses.append("project_id = ?")
            params.append(project_id)
        where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
        cur = conn.execute(
            f"SELECT * FROM datasets{where} ORDER BY upload_time DESC",
            params,
        )
        return [dict(r) for r in cur.fetchall()]


def get_dataset(dataset_id: int) -> Optional[Dict[str, Any]]:
    with _connect_ro() as conn:
        row = conn.execute("SELECT * FROM datasets WHERE id = ?", (dataset_id,)).fetchone()
        return dict(row) if row else None


def get_dataset_preview(
    dataset_id: int,
    job_title_col: Optional[str] = None,
    emp_col: Optional[str] = None,
) -> Dict[str, Any]:
    """Lightweight org-structure preview for the dataset selector cards.

    Returns the root node label and the first few level-2 (direct reports)
    labels, prefering the configured job-title column then "Job Title", then
    emp_id as a last-resort fallback. Cheap enough to call for every dataset
    on the list page (two indexed queries per dataset).
    """
    def _label(data: Dict[str, Any], emp_id: str) -> str:
        if job_title_col and data.get(job_title_col):
            return str(data[job_title_col])
        if data.get("Job Title"):
            return str(data["Job Title"])
        if emp_col and data.get(emp_col):
            return str(data[emp_col])
        return str(emp_id)

    with _connect_ro() as conn:
        root_row = conn.execute(
            "SELECT data_json, emp_id FROM baseline_records "
            "WHERE dataset_id = ? AND level = 1 ORDER BY id LIMIT 1",
            (dataset_id,),
        ).fetchone()
        root = None
        if root_row:
            try:
                data = json.loads(root_row["data_json"])
            except Exception:
                data = {}
            root = {"emp_id": root_row["emp_id"], "label": _label(data, root_row["emp_id"])}

        child_rows = conn.execute(
            "SELECT data_json, emp_id FROM baseline_records "
            "WHERE dataset_id = ? AND level = 2 ORDER BY id LIMIT 4",
            (dataset_id,),
        ).fetchall()
        children = []
        for r in child_rows:
            try:
                data = json.loads(r["data_json"])
            except Exception:
                data = {}
            children.append({"emp_id": r["emp_id"], "label": _label(data, r["emp_id"])})

        total_l2_row = conn.execute(
            "SELECT COUNT(*) AS n FROM baseline_records WHERE dataset_id = ? AND level = 2",
            (dataset_id,),
        ).fetchone()
        total_l2 = total_l2_row["n"] if total_l2_row else 0

        return {"root": root, "children": children, "total_children": total_l2}


def get_dataset_meta(dataset_id: int) -> Dict[str, Any]:
    """Aggregate metadata (scenario count, last activity, promoted scenario)
    used by the dataset selector cards."""
    with _connect_ro() as conn:
        rows = conn.execute(
            "SELECT name, is_promoted, updated_at FROM scenarios WHERE dataset_id = ?",
            (dataset_id,),
        ).fetchall()
        scenario_count = len(rows)
        last_modified: Optional[str] = None
        promoted_name: Optional[str] = None
        for r in rows:
            ts = r["updated_at"]
            if ts and (last_modified is None or ts > last_modified):
                last_modified = ts
            if r["is_promoted"]:
                promoted_name = r["name"]
        return {
            "scenario_count": scenario_count,
            "last_modified_at": last_modified,
            "promoted_scenario_name": promoted_name,
        }


def get_baseline_records(dataset_id: int) -> List[Dict[str, Any]]:
    with _connect_ro() as conn:
        cur = conn.execute(
            "SELECT data_json FROM baseline_records WHERE dataset_id = ?",
            (dataset_id,),
        )
        return [json.loads(r["data_json"]) for r in cur.fetchall()]


def delete_dataset(dataset_id: int) -> None:
    with _connect() as conn:
        conn.execute("DELETE FROM datasets WHERE id = ?", (dataset_id,))
        conn.commit()


# ---------------------------------------------------------------------------
# Scenarios
# ---------------------------------------------------------------------------

def list_scenarios(dataset_id: int) -> List[Dict[str, Any]]:
    with _connect_ro() as conn:
        cur = conn.execute(
            "SELECT * FROM scenarios WHERE dataset_id = ? ORDER BY created_at",
            (dataset_id,),
        )
        return [dict(r) for r in cur.fetchall()]


def get_scenario(scenario_id: int) -> Optional[Dict[str, Any]]:
    with _connect_ro() as conn:
        row = conn.execute("SELECT * FROM scenarios WHERE id = ?", (scenario_id,)).fetchone()
        return dict(row) if row else None


def create_scenario(
    dataset_id: int,
    name: str,
    description: str = "",
    source_scenario_id: Optional[int] = None,
    rate_card_id: Optional[int] = None,
    rate_card_quartile: str = "p50",
) -> int:
    """Create a new scenario. If `source_scenario_id` is provided, the new
    scenario starts as a deep copy of that scenario's current state; otherwise
    it forks the baseline."""
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()
        quartile = (rate_card_quartile or "p50").lower()
        if quartile not in ("p25", "p50", "p75"):
            quartile = "p50"
        c.execute(
            """
            INSERT INTO scenarios
                (dataset_id, name, description, created_at, updated_at, is_promoted,
                 rate_card_id, rate_card_quartile)
            VALUES (?, ?, ?, ?, ?, 0, ?, ?)
            """,
            (dataset_id, name, description, now, now, rate_card_id, quartile),
        )
        new_id = c.lastrowid

        if source_scenario_id is not None:
            c.execute(
                """
                INSERT INTO scenario_records
                    (scenario_id, emp_id, mgr_id, level, fte, flc,
                     is_flagged_removed, is_added, data_json)
                SELECT ?, emp_id, mgr_id, level, fte, flc,
                       is_flagged_removed, is_added, data_json
                FROM scenario_records WHERE scenario_id = ?
                """,
                (new_id, source_scenario_id),
            )
        else:
            c.execute(
                """
                INSERT INTO scenario_records
                    (scenario_id, emp_id, mgr_id, level, fte, flc,
                     is_flagged_removed, is_added, data_json)
                SELECT ?, emp_id, mgr_id, level, fte, flc, 0, 0, data_json
                FROM baseline_records WHERE dataset_id = ?
                """,
                (new_id, dataset_id),
            )

        conn.commit()
        return new_id


def rename_scenario(scenario_id: int, new_name: str, description: Optional[str] = None) -> None:
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        if description is not None:
            conn.execute(
                "UPDATE scenarios SET name = ?, description = ?, updated_at = ? WHERE id = ?",
                (new_name, description, now, scenario_id),
            )
        else:
            conn.execute(
                "UPDATE scenarios SET name = ?, updated_at = ? WHERE id = ?",
                (new_name, now, scenario_id),
            )
        conn.commit()


def delete_scenario(scenario_id: int) -> None:
    with _connect() as conn:
        conn.execute("DELETE FROM scenarios WHERE id = ?", (scenario_id,))
        conn.commit()


def get_scenario_records(scenario_id: int) -> List[Dict[str, Any]]:
    """Return all records for a scenario as merged dicts.

    Each record's stored JSON is merged with the mutable scenario columns
    (mgr_id, level, is_flagged_removed, is_added) so the frontend always sees
    the current state.
    """
    with _connect_ro() as conn:
        cur = conn.execute(
            """
            SELECT emp_id, mgr_id, level, fte, flc,
                   is_flagged_removed, is_added, data_json
            FROM scenario_records WHERE scenario_id = ?
            """,
            (scenario_id,),
        )
        records = []
        for r in cur.fetchall():
            data = json.loads(r["data_json"])
            data["__emp_id"] = r["emp_id"]
            data["__mgr_id"] = r["mgr_id"]
            data["Level"] = r["level"]
            data["is_flagged_removed"] = bool(r["is_flagged_removed"])
            data["is_added"] = bool(r["is_added"])
            records.append(data)
        return records


def promote_scenario(scenario_id: int) -> None:
    """Promote a scenario to be the new baseline.

    The scenario's current state replaces the dataset's baseline_records.
    The scenario itself is marked as is_promoted = 1.
    """
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()

        scenario = c.execute("SELECT * FROM scenarios WHERE id = ?", (scenario_id,)).fetchone()
        if not scenario:
            raise ValueError(f"Scenario {scenario_id} not found")
        dataset_id = scenario["dataset_id"]

        c.execute("DELETE FROM baseline_records WHERE dataset_id = ?", (dataset_id,))
        c.execute(
            """
            INSERT INTO baseline_records (dataset_id, emp_id, mgr_id, level, fte, flc, data_json)
            SELECT ?, emp_id, mgr_id, level, fte, flc, data_json
            FROM scenario_records
            WHERE scenario_id = ? AND is_flagged_removed = 0
            """,
            (dataset_id, scenario_id),
        )

        c.execute(
            "UPDATE scenarios SET is_promoted = 0 WHERE dataset_id = ?",
            (dataset_id,),
        )
        c.execute(
            "UPDATE scenarios SET is_promoted = 1, updated_at = ? WHERE id = ?",
            (now, scenario_id),
        )
        conn.commit()


# ---------------------------------------------------------------------------
# Scenario mutations (move / edit / add / flag)
# ---------------------------------------------------------------------------

def move_employee(
    scenario_id: int,
    emp_id: str,
    new_mgr_id: Optional[str],
    username: str = "",
) -> Dict[str, Any]:
    """Reassign an employee to a new manager. Returns the updated record."""
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()
        cur = c.execute(
            "SELECT mgr_id, data_json FROM scenario_records WHERE scenario_id = ? AND emp_id = ?",
            (scenario_id, emp_id),
        )
        row = cur.fetchone()
        if not row:
            raise ValueError(f"Employee {emp_id} not found in scenario {scenario_id}")
        old_mgr_id = row["mgr_id"]
        data = json.loads(row["data_json"])

        c.execute(
            "UPDATE scenario_records SET mgr_id = ? WHERE scenario_id = ? AND emp_id = ?",
            (new_mgr_id, scenario_id, emp_id),
        )
        c.execute(
            """
            INSERT INTO change_log
                (scenario_id, action, emp_id, old_mgr_id, new_mgr_id, timestamp, username)
            VALUES (?, 'move', ?, ?, ?, ?, ?)
            """,
            (scenario_id, emp_id, old_mgr_id, new_mgr_id, now, username),
        )
        c.execute("UPDATE scenarios SET updated_at = ? WHERE id = ?", (now, scenario_id))
        conn.commit()

        data["__emp_id"] = emp_id
        data["__mgr_id"] = new_mgr_id
        return data


def edit_employee(
    scenario_id: int,
    emp_id: str,
    updates: Dict[str, Any],
    username: str = "",
) -> Dict[str, Any]:
    """Edit arbitrary fields on an employee. Updates JSON blob + hot columns."""
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()
        row = c.execute(
            """
            SELECT mgr_id, level, fte, flc, data_json
            FROM scenario_records WHERE scenario_id = ? AND emp_id = ?
            """,
            (scenario_id, emp_id),
        ).fetchone()
        if not row:
            raise ValueError(f"Employee {emp_id} not found in scenario {scenario_id}")

        data = json.loads(row["data_json"])
        new_mgr_id = row["mgr_id"]
        new_level = row["level"]
        new_fte = row["fte"]
        new_flc = row["flc"]

        for field, new_value in updates.items():
            old_value = data.get(field)
            data[field] = new_value
            c.execute(
                """
                INSERT INTO change_log
                    (scenario_id, action, emp_id, field, old_value, new_value, timestamp, username)
                VALUES (?, 'edit', ?, ?, ?, ?, ?, ?)
                """,
                (scenario_id, emp_id, field, _to_str(old_value), _to_str(new_value), now, username),
            )
            # Mirror updates to hot columns where applicable
            if field == "Level":
                new_level = _to_int(new_value)
            elif field == "fte" or field.lower() == "fte":
                new_fte = _to_float(new_value)
            elif field == "flc" or field.lower() == "flc":
                new_flc = _to_float(new_value)

        c.execute(
            """
            UPDATE scenario_records
            SET data_json = ?, level = ?, fte = ?, flc = ?
            WHERE scenario_id = ? AND emp_id = ?
            """,
            (json.dumps(data, default=str), new_level, new_fte, new_flc, scenario_id, emp_id),
        )
        c.execute("UPDATE scenarios SET updated_at = ? WHERE id = ?", (now, scenario_id))
        conn.commit()

        data["__emp_id"] = emp_id
        data["__mgr_id"] = new_mgr_id
        return data


def add_employee(
    scenario_id: int,
    record: Dict[str, Any],
    emp_id: str,
    mgr_id: Optional[str],
    level: Optional[int] = None,
    fte: Optional[float] = None,
    flc: Optional[float] = None,
    username: str = "",
) -> Dict[str, Any]:
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()
        c.execute(
            """
            INSERT INTO scenario_records
                (scenario_id, emp_id, mgr_id, level, fte, flc,
                 is_flagged_removed, is_added, data_json)
            VALUES (?, ?, ?, ?, ?, ?, 0, 1, ?)
            """,
            (scenario_id, emp_id, mgr_id, level, fte, flc, json.dumps(record, default=str)),
        )
        c.execute(
            """
            INSERT INTO change_log
                (scenario_id, action, emp_id, new_mgr_id, timestamp, username)
            VALUES (?, 'add', ?, ?, ?, ?)
            """,
            (scenario_id, emp_id, mgr_id, now, username),
        )
        c.execute("UPDATE scenarios SET updated_at = ? WHERE id = ?", (now, scenario_id))
        conn.commit()

        record = dict(record)
        record["__emp_id"] = emp_id
        record["__mgr_id"] = mgr_id
        record["is_added"] = True
        record["is_flagged_removed"] = False
        return record


def clone_employee(
    scenario_id: int,
    source_emp_id: str,
    new_emp_id: str,
    new_mgr_id: Optional[str] = None,
    username: str = "",
) -> Dict[str, Any]:
    """Clone an existing position into a new scenario record (is_added=1)."""
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()
        row = c.execute(
            """
            SELECT mgr_id, level, fte, flc, data_json
            FROM scenario_records WHERE scenario_id = ? AND emp_id = ?
            """,
            (scenario_id, source_emp_id),
        ).fetchone()
        if not row:
            raise ValueError(f"Employee {source_emp_id} not found in scenario {scenario_id}")

        dup = c.execute(
            "SELECT id FROM scenario_records WHERE scenario_id = ? AND emp_id = ?",
            (scenario_id, new_emp_id),
        ).fetchone()
        if dup:
            raise ValueError(f"Employee ID {new_emp_id} already exists in this scenario")

        data = json.loads(row["data_json"])
        mgr_id = new_mgr_id if new_mgr_id is not None else row["mgr_id"]
        level = row["level"]
        fte = row["fte"]
        flc = row["flc"]

        scenario = c.execute(
            "SELECT dataset_id FROM scenarios WHERE id = ?", (scenario_id,)
        ).fetchone()
        dataset = c.execute(
            "SELECT emp_col, mgr_col FROM datasets WHERE id = ?",
            (scenario["dataset_id"],),
        ).fetchone()
        if dataset:
            if dataset["emp_col"]:
                data[dataset["emp_col"]] = new_emp_id
            if dataset["mgr_col"]:
                data[dataset["mgr_col"]] = mgr_id

        c.execute(
            """
            INSERT INTO scenario_records
                (scenario_id, emp_id, mgr_id, level, fte, flc,
                 is_flagged_removed, is_added, data_json)
            VALUES (?, ?, ?, ?, ?, ?, 0, 1, ?)
            """,
            (scenario_id, new_emp_id, mgr_id, level, fte, flc, json.dumps(data, default=str)),
        )
        c.execute(
            """
            INSERT INTO change_log
                (scenario_id, action, emp_id, field, old_value, new_mgr_id, timestamp, username)
            VALUES (?, 'clone', ?, 'source_emp_id', ?, ?, ?, ?)
            """,
            (scenario_id, new_emp_id, source_emp_id, mgr_id, now, username),
        )
        c.execute("UPDATE scenarios SET updated_at = ? WHERE id = ?", (now, scenario_id))
        conn.commit()

        data["__emp_id"] = new_emp_id
        data["__mgr_id"] = mgr_id
        data["Level"] = level
        data["is_added"] = True
        data["is_flagged_removed"] = False
        return data


def flag_employee(
    scenario_id: int,
    emp_id: str,
    flagged: bool,
    username: str = "",
) -> Dict[str, Any]:
    """Flag/unflag an employee and cascade to all descendants."""
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()
        root_row = c.execute(
            "SELECT mgr_id, data_json FROM scenario_records WHERE scenario_id = ? AND emp_id = ?",
            (scenario_id, emp_id),
        ).fetchone()
        if not root_row:
            raise ValueError(f"Employee {emp_id} not found in scenario {scenario_id}")

        subtree_rows = c.execute(
            """
            WITH RECURSIVE subtree AS (
                SELECT emp_id FROM scenario_records
                WHERE scenario_id = ? AND emp_id = ?
              UNION ALL
                SELECT sr.emp_id FROM scenario_records sr
                JOIN subtree st ON sr.mgr_id = st.emp_id
                WHERE sr.scenario_id = ?
            )
            SELECT emp_id FROM subtree
            """,
            (scenario_id, emp_id, scenario_id),
        ).fetchall()

        affected_ids = [r["emp_id"] for r in subtree_rows]
        placeholders = ",".join("?" * len(affected_ids))
        c.execute(
            f"UPDATE scenario_records SET is_flagged_removed = ? "
            f"WHERE scenario_id = ? AND emp_id IN ({placeholders})",
            [1 if flagged else 0, scenario_id] + affected_ids,
        )
        c.execute(
            """
            INSERT INTO change_log
                (scenario_id, action, emp_id, timestamp, username)
            VALUES (?, ?, ?, ?, ?)
            """,
            (scenario_id, "flag_remove" if flagged else "unflag_restore", emp_id, now, username),
        )
        c.execute("UPDATE scenarios SET updated_at = ? WHERE id = ?", (now, scenario_id))
        conn.commit()

        data = json.loads(root_row["data_json"])
        data["__emp_id"] = emp_id
        data["__mgr_id"] = root_row["mgr_id"]
        data["is_flagged_removed"] = flagged
        return data


def delete_scenario_record(scenario_id: int, emp_id: str, username: str = "") -> None:
    """Hard-delete a scenario record (use sparingly -- soft-delete via flag is preferred).
    Only allowed for records added in this scenario (is_added = 1)."""
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()
        row = c.execute(
            "SELECT is_added FROM scenario_records WHERE scenario_id = ? AND emp_id = ?",
            (scenario_id, emp_id),
        ).fetchone()
        if not row:
            raise ValueError(f"Employee {emp_id} not found in scenario {scenario_id}")
        if not row["is_added"]:
            raise ValueError("Cannot hard-delete baseline records; use flag_employee instead")

        c.execute(
            "DELETE FROM scenario_records WHERE scenario_id = ? AND emp_id = ?",
            (scenario_id, emp_id),
        )
        c.execute(
            """
            INSERT INTO change_log (scenario_id, action, emp_id, timestamp, username)
            VALUES (?, 'delete', ?, ?, ?)
            """,
            (scenario_id, emp_id, now, username),
        )
        c.execute("UPDATE scenarios SET updated_at = ? WHERE id = ?", (now, scenario_id))
        conn.commit()


# ---------------------------------------------------------------------------
# Revert / undo
# ---------------------------------------------------------------------------

def reset_scenario_to_baseline(scenario_id: int, username: str = "") -> None:
    """Wipe all changes in a scenario and re-copy from the dataset baseline."""
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()
        scenario = c.execute("SELECT * FROM scenarios WHERE id = ?", (scenario_id,)).fetchone()
        if not scenario:
            raise ValueError(f"Scenario {scenario_id} not found")
        dataset_id = scenario["dataset_id"]

        c.execute("DELETE FROM scenario_records WHERE scenario_id = ?", (scenario_id,))
        c.execute("DELETE FROM change_log WHERE scenario_id = ?", (scenario_id,))
        c.execute(
            """
            INSERT INTO scenario_records
                (scenario_id, emp_id, mgr_id, level, fte, flc,
                 is_flagged_removed, is_added, data_json)
            SELECT ?, emp_id, mgr_id, level, fte, flc, 0, 0, data_json
            FROM baseline_records WHERE dataset_id = ?
            """,
            (scenario_id, dataset_id),
        )
        c.execute(
            """
            INSERT INTO change_log (scenario_id, action, emp_id, timestamp, username)
            VALUES (?, 'reset', '', ?, ?)
            """,
            (scenario_id, now, username),
        )
        c.execute("UPDATE scenarios SET updated_at = ? WHERE id = ?", (now, scenario_id))
        conn.commit()


def undo_last_change(scenario_id: int, username: str = "") -> Optional[Dict[str, Any]]:
    """Reverse the most recent change_log entry for a scenario.

    Returns the reversed log entry dict, or None if there's nothing to undo.
    Only move, edit, flag_remove, unflag_restore, add, and clone actions can be undone.
    """
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()
        last = c.execute(
            "SELECT * FROM change_log WHERE scenario_id = ? ORDER BY id DESC LIMIT 1",
            (scenario_id,),
        ).fetchone()
        if not last:
            return None
        entry = dict(last)
        action = entry["action"]

        if action == "move":
            c.execute(
                "UPDATE scenario_records SET mgr_id = ? WHERE scenario_id = ? AND emp_id = ?",
                (entry["old_mgr_id"], scenario_id, entry["emp_id"]),
            )
        elif action == "edit":
            row = c.execute(
                "SELECT data_json FROM scenario_records WHERE scenario_id = ? AND emp_id = ?",
                (scenario_id, entry["emp_id"]),
            ).fetchone()
            if row:
                data = json.loads(row["data_json"])
                data[entry["field"]] = entry["old_value"]
                new_level = data.get("Level")
                new_fte = _to_float(data.get("fte", data.get("FTE")))
                new_flc = _to_float(data.get("flc", data.get("FLC")))
                if entry["field"] == "Level":
                    new_level = _to_int(entry["old_value"])
                elif entry["field"].lower() == "fte":
                    new_fte = _to_float(entry["old_value"])
                elif entry["field"].lower() == "flc":
                    new_flc = _to_float(entry["old_value"])
                c.execute(
                    """
                    UPDATE scenario_records
                    SET data_json = ?, level = ?, fte = ?, flc = ?
                    WHERE scenario_id = ? AND emp_id = ?
                    """,
                    (json.dumps(data, default=str), new_level, new_fte, new_flc,
                     scenario_id, entry["emp_id"]),
                )
        elif action == "flag_remove":
            c.execute(
                "UPDATE scenario_records SET is_flagged_removed = 0 WHERE scenario_id = ? AND emp_id = ?",
                (scenario_id, entry["emp_id"]),
            )
        elif action == "unflag_restore":
            c.execute(
                "UPDATE scenario_records SET is_flagged_removed = 1 WHERE scenario_id = ? AND emp_id = ?",
                (scenario_id, entry["emp_id"]),
            )
        elif action in ("add", "clone"):
            c.execute(
                "DELETE FROM scenario_records WHERE scenario_id = ? AND emp_id = ? AND is_added = 1",
                (scenario_id, entry["emp_id"]),
            )
        elif action == "reset":
            c.execute("DELETE FROM change_log WHERE id = ?", (entry["id"],))
            conn.commit()
            return entry
        else:
            c.execute("DELETE FROM change_log WHERE id = ?", (entry["id"],))
            conn.commit()
            return entry

        c.execute("DELETE FROM change_log WHERE id = ?", (entry["id"],))
        c.execute("UPDATE scenarios SET updated_at = ? WHERE id = ?", (now, scenario_id))
        conn.commit()
        return entry


# ---------------------------------------------------------------------------
# Change log + summary stats
# ---------------------------------------------------------------------------

def get_change_log(scenario_id: int) -> List[Dict[str, Any]]:
    with _connect_ro() as conn:
        cur = conn.execute(
            "SELECT * FROM change_log WHERE scenario_id = ? ORDER BY id",
            (scenario_id,),
        )
        return [dict(r) for r in cur.fetchall()]


# ---------------------------------------------------------------------------
# Dataset activity feed (per-user "last seen" tracking + recent changes query)
# ---------------------------------------------------------------------------

def get_dataset_last_seen(dataset_id: int, user_id: int) -> Optional[str]:
    with _connect_ro() as conn:
        row = conn.execute(
            "SELECT last_seen FROM dataset_user_views WHERE dataset_id = ? AND user_id = ?",
            (dataset_id, user_id),
        ).fetchone()
        return row["last_seen"] if row else None


def mark_dataset_seen(dataset_id: int, user_id: int) -> str:
    """Record that this user has viewed this dataset at this moment.
    UPSERT on (dataset_id, user_id). Returns the ISO timestamp written."""
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        conn.execute(
            """
            INSERT INTO dataset_user_views (dataset_id, user_id, last_seen)
            VALUES (?, ?, ?)
            ON CONFLICT(dataset_id, user_id)
            DO UPDATE SET last_seen = EXCLUDED.last_seen
            """,
            (dataset_id, user_id, now),
        )
        conn.commit()
    return now


def get_dataset_recent_changes(
    dataset_id: int,
    user_id: int,
    *,
    since: Optional[str] = None,
    limit: int = 50,
    current_username: Optional[str] = None,
) -> Dict[str, Any]:
    """Return change_log entries across every scenario in this dataset, plus
    metadata describing which are unseen by this user.

    - `since` overrides the stored last_seen for the user (used when the
      caller already knows the cut-off, e.g. for pagination).
    - Entries authored by the current user are never counted as "unseen" --
      you don't need to be notified about your own edits.
    """
    last_seen = since if since is not None else get_dataset_last_seen(dataset_id, user_id)

    with _connect_ro() as conn:
        rows = conn.execute(
            """
            SELECT cl.id, cl.scenario_id, cl.action, cl.emp_id,
                   cl.old_mgr_id, cl.new_mgr_id, cl.field,
                   cl.old_value, cl.new_value, cl.timestamp, cl.username,
                   s.name AS scenario_name
            FROM change_log cl
            JOIN scenarios s ON s.id = cl.scenario_id
            WHERE s.dataset_id = ?
            ORDER BY cl.timestamp DESC, cl.id DESC
            LIMIT ?
            """,
            (dataset_id, limit),
        ).fetchall()

        changes: List[Dict[str, Any]] = []
        unseen_count = 0
        contributors: Dict[str, int] = {}
        action_counts: Dict[str, int] = {}

        for r in rows:
            d = dict(r)
            ts = d.get("timestamp")
            is_self = (current_username is not None and d.get("username") == current_username)
            is_unseen = (
                not is_self
                and ts is not None
                and (last_seen is None or ts > last_seen)
            )
            d["is_unseen"] = is_unseen
            changes.append(d)
            if is_unseen:
                unseen_count += 1
                uname = d.get("username") or "Unknown"
                contributors[uname] = contributors.get(uname, 0) + 1
                action = d.get("action") or "other"
                action_counts[action] = action_counts.get(action, 0) + 1

        return {
            "changes": changes,
            "unseen_count": unseen_count,
            "last_seen_at": last_seen,
            "contributors": [
                {"username": name, "change_count": cnt}
                for name, cnt in sorted(contributors.items(), key=lambda kv: -kv[1])
            ],
            "action_counts": action_counts,
        }


def get_scenario_summary(scenario_id: int) -> Dict[str, Any]:
    """Aggregate summary stats for a scenario, excluding flagged-removed rows."""
    with _connect_ro() as conn:
        scenario = conn.execute(
            "SELECT * FROM scenarios WHERE id = ?", (scenario_id,)
        ).fetchone()
        if not scenario:
            raise ValueError(f"Scenario {scenario_id} not found")
        dataset_id = scenario["dataset_id"]

        active = conn.execute(
            """
            SELECT COUNT(*) AS headcount,
                   COALESCE(SUM(fte), 0) AS total_fte,
                   COALESCE(SUM(flc), 0) AS total_cost
            FROM scenario_records
            WHERE scenario_id = ? AND is_flagged_removed = 0
            """,
            (scenario_id,),
        ).fetchone()

        flagged = conn.execute(
            """
            SELECT COUNT(*) AS removed_count,
                   COALESCE(SUM(fte), 0) AS removed_fte,
                   COALESCE(SUM(flc), 0) AS removed_cost
            FROM scenario_records
            WHERE scenario_id = ? AND is_flagged_removed = 1
            """,
            (scenario_id,),
        ).fetchone()

        baseline = conn.execute(
            """
            SELECT COUNT(*) AS headcount,
                   COALESCE(SUM(fte), 0) AS total_fte,
                   COALESCE(SUM(flc), 0) AS total_cost
            FROM baseline_records WHERE dataset_id = ?
            """,
            (dataset_id,),
        ).fetchone()

        change_count = conn.execute(
            "SELECT COUNT(*) AS n FROM change_log WHERE scenario_id = ?",
            (scenario_id,),
        ).fetchone()

    return {
        "scenario_id": scenario_id,
        "dataset_id": dataset_id,
        "scenario_name": scenario["name"],
        "is_promoted": bool(scenario["is_promoted"]),
        "current": {
            "headcount": active["headcount"],
            "total_fte": float(active["total_fte"] or 0),
            "total_cost": float(active["total_cost"] or 0),
        },
        "baseline": {
            "headcount": baseline["headcount"],
            "total_fte": float(baseline["total_fte"] or 0),
            "total_cost": float(baseline["total_cost"] or 0),
        },
        "flagged_removed": {
            "count": flagged["removed_count"],
            "fte": float(flagged["removed_fte"] or 0),
            "cost": float(flagged["removed_cost"] or 0),
        },
        "delta": {
            "headcount": active["headcount"] - baseline["headcount"],
            "fte": float(active["total_fte"] or 0) - float(baseline["total_fte"] or 0),
            "cost": float(active["total_cost"] or 0) - float(baseline["total_cost"] or 0),
        },
        "change_count": change_count["n"],
    }


def _dim_value_from_json(data_json: str, dimension_col: str) -> str:
    try:
        data = json.loads(data_json)
        val = data.get(dimension_col)
        if val is None or str(val).strip() == "":
            return "(Blank)"
        return str(val).strip()
    except Exception:
        return "(Blank)"


def get_scenario_summary_by_dimension(
    scenario_id: int,
    dimension_col: str,
) -> Dict[str, Any]:
    """Return baseline vs to-be breakdown grouped by a census dimension column.

    Each employee contributes to baseline at their baseline dimension value and
    to to-be at their current (active) scenario dimension value, so moves between
    departments/countries show correctly as deltas on both sides.
    """
    if not dimension_col or not str(dimension_col).strip():
        raise ValueError("dimension_col is required")

    dimension_col = str(dimension_col).strip()

    with _connect_ro() as conn:
        scenario = conn.execute(
            "SELECT * FROM scenarios WHERE id = ?", (scenario_id,)
        ).fetchone()
        if not scenario:
            raise ValueError(f"Scenario {scenario_id} not found")
        dataset_id = scenario["dataset_id"]

        baseline_rows = conn.execute(
            "SELECT emp_id, mgr_id, level, fte, flc, data_json FROM baseline_records WHERE dataset_id = ?",
            (dataset_id,),
        ).fetchall()

        scenario_rows = conn.execute(
            """
            SELECT emp_id, mgr_id, level, fte, flc, is_flagged_removed, data_json
            FROM scenario_records WHERE scenario_id = ?
            """,
            (scenario_id,),
        ).fetchall()

    # Validate column exists in at least one record
    sample_json = None
    if baseline_rows:
        sample_json = baseline_rows[0]["data_json"]
    elif scenario_rows:
        sample_json = scenario_rows[0]["data_json"]
    if sample_json:
        try:
            keys = set(json.loads(sample_json).keys())
            if dimension_col not in keys and dimension_col != "Level":
                raise ValueError(
                    f"Column '{dimension_col}' not found in dataset records. "
                    f"Available columns include: {', '.join(sorted(keys)[:12])}…"
                )
        except json.JSONDecodeError:
            pass

    def _accum(bucket_map: Dict[str, Dict[str, float]], dim_val: str, fte: float, cost: float) -> None:
        b = bucket_map.setdefault(dim_val, {"headcount": 0, "fte": 0.0, "cost": 0.0})
        b["headcount"] += 1
        b["fte"] += fte
        b["cost"] += cost

    def _row_dim_val(row) -> str:
        if dimension_col == "Level":
            lv = row["level"]
            return str(lv) if lv is not None else "(Blank)"
        return _dim_value_from_json(row["data_json"], dimension_col)

    baseline_buckets: Dict[str, Dict[str, float]] = {}
    for r in baseline_rows:
        _accum(baseline_buckets, _row_dim_val(r), float(r["fte"] or 0), float(r["flc"] or 0))

    tobe_buckets: Dict[str, Dict[str, float]] = {}
    for r in scenario_rows:
        if r["is_flagged_removed"]:
            continue
        _accum(tobe_buckets, _row_dim_val(r), float(r["fte"] or 0), float(r["flc"] or 0))

    all_values = sorted(
        set(baseline_buckets.keys()) | set(tobe_buckets.keys()),
        key=lambda s: (s == "(Blank)", s.lower()),
    )

    rows: List[Dict[str, Any]] = []
    tot_b_hc = tot_b_fte = tot_b_cost = 0
    tot_t_hc = tot_t_fte = tot_t_cost = 0

    for dv in all_values:
        b = baseline_buckets.get(dv, {"headcount": 0, "fte": 0.0, "cost": 0.0})
        t = tobe_buckets.get(dv, {"headcount": 0, "fte": 0.0, "cost": 0.0})
        b_hc, b_fte, b_cost = int(b["headcount"]), float(b["fte"]), float(b["cost"])
        t_hc, t_fte, t_cost = int(t["headcount"]), float(t["fte"]), float(t["cost"])
        tot_b_hc += b_hc
        tot_b_fte += b_fte
        tot_b_cost += b_cost
        tot_t_hc += t_hc
        tot_t_fte += t_fte
        tot_t_cost += t_cost
        rows.append({
            "dimension_value": dv,
            "baseline_hc": b_hc,
            "baseline_fte": round(b_fte, 2),
            "baseline_cost": round(b_cost, 2),
            "tobe_hc": t_hc,
            "tobe_fte": round(t_fte, 2),
            "tobe_cost": round(t_cost, 2),
            "delta_hc": t_hc - b_hc,
            "delta_fte": round(t_fte - b_fte, 2),
            "delta_cost": round(t_cost - b_cost, 2),
        })

    return {
        "scenario_id": scenario_id,
        "dimension_col": dimension_col,
        "rows": rows,
        "totals": {
            "dimension_value": "Total",
            "baseline_hc": tot_b_hc,
            "baseline_fte": round(tot_b_fte, 2),
            "baseline_cost": round(tot_b_cost, 2),
            "tobe_hc": tot_t_hc,
            "tobe_fte": round(tot_t_fte, 2),
            "tobe_cost": round(tot_t_cost, 2),
            "delta_hc": tot_t_hc - tot_b_hc,
            "delta_fte": round(tot_t_fte - tot_b_fte, 2),
            "delta_cost": round(tot_t_cost - tot_b_cost, 2),
        },
    }


def get_export_dimension_columns(dataset_id: int, max_cols: int = 8) -> List[str]:
    """Return dimension columns suitable for multi-sheet changes export."""
    meta = get_dataset_columns(dataset_id)
    column_meta = meta.get("column_meta") or {}
    dims = [c for c in meta.get("columns", []) if column_meta.get(c, {}).get("is_dimension")]
    # Always include Level if present
    cols = meta.get("columns", [])
    if "Level" in cols and "Level" not in dims:
        dims = ["Level"] + dims
    preferred = ["Country", "Department", "Division", "Grade", "Job Grade", "Location", "Level"]
    ordered: List[str] = []
    for p in preferred:
        if p in dims and p not in ordered:
            ordered.append(p)
    for d in dims:
        if d not in ordered:
            ordered.append(d)
    return ordered[:max_cols]


# ---------------------------------------------------------------------------
# Rate cards
# ---------------------------------------------------------------------------

def get_dataset_columns(dataset_id: int) -> Dict[str, Any]:
    """Return columns that actually exist in baseline records, with metadata.

    Returns:
        {
          "columns": [str, ...],        # sorted column names
          "column_meta": {              # per-column metadata
            "<col>": {
              "unique_count": int,
              "sample_values": [str, ...],  # up to 5 distinct values
              "is_dimension": bool,         # good candidate for grouping
              "is_cost": bool,              # cost/numeric measure
            }
          }
        }
    """
    dataset = get_dataset(dataset_id)
    if not dataset:
        raise ValueError(f"Dataset {dataset_id} not found")

    emp_col = dataset.get("emp_col") or ""
    mgr_col = dataset.get("mgr_col") or ""
    flc_col = dataset.get("flc_col") or ""
    fte_col = dataset.get("fte_col") or ""

    # system / id columns to exclude from grouping suggestions
    id_cols = {emp_col.lower(), mgr_col.lower()}
    # column name substrings that suggest a cost/numeric measure
    # use whole-word / prefix checks to avoid false positives like "country" matching "count"
    _cost_word_hints = {"pay", "cost", "flc", "bonus", "salary", "allowance",
                        "compensation", "fte", "basic"}
    _cost_prefix_hints = {"add on", "on-target"}  # must appear at start or after space

    def _is_cost_col(col_lower: str) -> bool:
        import re
        # exact word boundary match for each hint
        for h in _cost_word_hints:
            if re.search(r"(?<![a-z])" + re.escape(h) + r"(?![a-z])", col_lower):
                return True
        for h in _cost_prefix_hints:
            if h in col_lower:
                return True
        return False
    # computed chain columns
    _chain_hints = {"chain", "l1", "l2", "l3", "l4", "l5", "last_employee", "span", "total_reports"}

    with _connect_ro() as conn:
        rows = conn.execute(
            "SELECT data_json FROM baseline_records WHERE dataset_id = ? LIMIT 500",
            (dataset_id,),
        ).fetchall()

    if not rows:
        return {"columns": [], "column_meta": {}}

    # accumulate unique values per column
    values_by_col: Dict[str, set] = {}
    for r in rows:
        try:
            rec = json.loads(r["data_json"])
        except Exception:
            continue
        for k, v in rec.items():
            if str(k).startswith("__"):
                continue
            col = str(k)
            if col not in values_by_col:
                values_by_col[col] = set()
            if v is not None and str(v).strip():
                values_by_col[col].add(str(v).strip())

    column_meta: Dict[str, Any] = {}
    for col, vals in values_by_col.items():
        col_lower = col.lower()
        unique_count = len(vals)

        is_id = col_lower in id_cols
        is_flag = (
            col_lower.startswith("flag_") or col_lower.startswith("flag ")
            or col_lower.endswith("_flag")
        )
        is_cost = (
            col_lower == (flc_col or "").lower()
            or col_lower == (fte_col or "").lower()
            or _is_cost_col(col_lower)
        )
        is_chain = any(col_lower == h or col_lower.startswith(h + "_") for h in _chain_hints)
        is_date = any(h in col_lower for h in ("date", "start", "end", "hire"))

        # Good grouping dimension: not an ID/flag/cost/chain/date, moderate cardinality
        is_dimension = (
            not is_id
            and not is_flag
            and not is_cost
            and not is_chain
            and not is_date
            and 2 <= unique_count <= 30
        )

        sample_values = sorted(vals)[:5]

        column_meta[col] = {
            "unique_count": unique_count,
            "sample_values": sample_values,
            "is_dimension": is_dimension,
            "is_cost": is_cost,
            "is_id": is_id,
            "is_flag": is_flag,
        }

    cols_sorted = sorted(values_by_col.keys(), key=lambda s: s.lower())
    return {"columns": cols_sorted, "column_meta": column_meta}


def list_rate_cards(dataset_id: int) -> List[Dict[str, Any]]:
    from services.rate_card_service import parse_property_cols

    with _connect_ro() as conn:
        cur = conn.execute(
            """
            SELECT rc.*, COUNT(r.id) AS row_count
            FROM rate_card_definitions rc
            LEFT JOIN rate_card_rows r ON r.rate_card_id = rc.id
            WHERE rc.dataset_id = ?
            GROUP BY rc.id
            ORDER BY rc.created_at DESC
            """,
            (dataset_id,),
        )
        rows = []
        for r in cur.fetchall():
            item = dict(r)
            item["property_cols"] = parse_property_cols(item.get("property_cols_json"))
            rows.append(item)
        return rows


def get_rate_card(rate_card_id: int) -> Optional[Dict[str, Any]]:
    from services.rate_card_service import parse_property_cols

    with _connect_ro() as conn:
        row = conn.execute(
            "SELECT * FROM rate_card_definitions WHERE id = ?", (rate_card_id,)
        ).fetchone()
        if not row:
            return None
        definition = dict(row)
        definition["property_cols"] = parse_property_cols(definition.get("property_cols_json"))
        definition["rows"] = [
            dict(r)
            for r in conn.execute(
                "SELECT * FROM rate_card_rows WHERE rate_card_id = ? ORDER BY composite_key",
                (rate_card_id,),
            ).fetchall()
        ]
        for r in definition["rows"]:
            r["is_manual_override"] = bool(r.get("is_manual_override"))
            r["is_available"] = r.get("p50") is not None or r.get("avg_cost") is not None
        return definition


def preview_rate_card(
    dataset_id: int,
    property_cols: List[str],
    cost_col: Optional[str] = None,
    min_sample: int = 3,
) -> List[Dict[str, Any]]:
    from services.rate_card_service import compute_rate_card_rows

    dataset = get_dataset(dataset_id)
    if not dataset:
        raise ValueError(f"Dataset {dataset_id} not found")
    resolved_cost = cost_col or dataset.get("flc_col") or "FLC"
    records = get_baseline_records(dataset_id)
    return compute_rate_card_rows(records, property_cols, resolved_cost, min_sample=min_sample)


def _insert_rate_card_rows(c, rate_card_id: int, rows: List[Dict[str, Any]]) -> None:
    for row in rows:
        c.execute(
            """
            INSERT INTO rate_card_rows
                (rate_card_id, composite_key, p25, p50, p75, avg_cost,
                 sample_count, is_manual_override)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT (rate_card_id, composite_key) DO UPDATE SET
                p25 = EXCLUDED.p25,
                p50 = EXCLUDED.p50,
                p75 = EXCLUDED.p75,
                avg_cost = EXCLUDED.avg_cost,
                sample_count = EXCLUDED.sample_count,
                is_manual_override = EXCLUDED.is_manual_override
            """,
            (
                rate_card_id,
                row["composite_key"],
                row.get("p25"),
                row.get("p50"),
                row.get("p75"),
                row.get("avg_cost"),
                int(row.get("sample_count") or 0),
                1 if row.get("is_manual_override") else 0,
            ),
        )


def create_rate_card_from_baseline(
    dataset_id: int,
    name: str,
    property_cols: List[str],
    cost_col: Optional[str] = None,
    min_sample: int = 3,
    created_by: str = "",
) -> int:
    from services.rate_card_service import compute_rate_card_rows

    dataset = get_dataset(dataset_id)
    if not dataset:
        raise ValueError(f"Dataset {dataset_id} not found")
    if not property_cols:
        raise ValueError("Select at least one property column")
    if len(property_cols) > 3:
        raise ValueError("Select up to three property columns")

    resolved_cost = cost_col or dataset.get("flc_col") or "FLC"
    rows = compute_rate_card_rows(
        get_baseline_records(dataset_id), property_cols, resolved_cost, min_sample=min_sample
    )
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()
        c.execute(
            """
            INSERT INTO rate_card_definitions
                (dataset_id, name, property_cols_json, cost_col, min_sample, created_at, created_by)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                dataset_id,
                name,
                json.dumps(property_cols),
                resolved_cost,
                min_sample,
                now,
                created_by,
            ),
        )
        rate_card_id = c.lastrowid
        _insert_rate_card_rows(c, rate_card_id, rows)
        conn.commit()
        return rate_card_id


def create_rate_card_from_rows(
    dataset_id: int,
    name: str,
    property_cols: List[str],
    cost_col: str,
    rows: List[Dict[str, Any]],
    min_sample: int = 3,
    created_by: str = "",
) -> int:
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        c = conn.cursor()
        c.execute(
            """
            INSERT INTO rate_card_definitions
                (dataset_id, name, property_cols_json, cost_col, min_sample, created_at, created_by)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                dataset_id,
                name,
                json.dumps(property_cols),
                cost_col,
                min_sample,
                now,
                created_by,
            ),
        )
        rate_card_id = c.lastrowid
        _insert_rate_card_rows(c, rate_card_id, rows)
        conn.commit()
        return rate_card_id


def upsert_rate_card_row(
    rate_card_id: int,
    composite_key: str,
    p25: Optional[float] = None,
    p50: Optional[float] = None,
    p75: Optional[float] = None,
    avg_cost: Optional[float] = None,
) -> None:
    with _connect() as conn:
        conn.execute(
            """
            INSERT INTO rate_card_rows
                (rate_card_id, composite_key, p25, p50, p75, avg_cost,
                 sample_count, is_manual_override)
            VALUES (?, ?, ?, ?, ?, ?, 0, 1)
            ON CONFLICT (rate_card_id, composite_key) DO UPDATE SET
                p25 = EXCLUDED.p25,
                p50 = EXCLUDED.p50,
                p75 = EXCLUDED.p75,
                avg_cost = EXCLUDED.avg_cost,
                is_manual_override = 1
            """,
            (rate_card_id, composite_key, p25, p50, p75, avg_cost),
        )
        conn.commit()


def set_scenario_rate_card(
    scenario_id: int,
    rate_card_id: Optional[int],
    quartile: str = "p50",
) -> Dict[str, Any]:
    q = (quartile or "p50").lower()
    if q not in ("p25", "p50", "p75"):
        q = "p50"
    now = datetime.utcnow().isoformat()
    with _connect() as conn:
        scenario = conn.execute(
            "SELECT * FROM scenarios WHERE id = ?", (scenario_id,)
        ).fetchone()
        if not scenario:
            raise ValueError(f"Scenario {scenario_id} not found")
        if rate_card_id is not None:
            rc = conn.execute(
                "SELECT dataset_id FROM rate_card_definitions WHERE id = ?",
                (rate_card_id,),
            ).fetchone()
            if not rc or rc["dataset_id"] != scenario["dataset_id"]:
                raise ValueError("Rate card does not belong to this dataset")
        conn.execute(
            """
            UPDATE scenarios
            SET rate_card_id = ?, rate_card_quartile = ?, updated_at = ?
            WHERE id = ?
            """,
            (rate_card_id, q, now, scenario_id),
        )
        conn.commit()
    updated = get_scenario(scenario_id)
    return updated or {}


def lookup_rate_card_cost(
    scenario_id: int,
    values: Dict[str, Any],
) -> Optional[Dict[str, Any]]:
    from services.rate_card_service import (
        build_composite_key,
        lookup_cost_from_row,
        parse_property_cols,
        quartile_value,
    )

    scenario = get_scenario(scenario_id)
    if not scenario or not scenario.get("rate_card_id"):
        return None
    rate_card = get_rate_card(int(scenario["rate_card_id"]))
    if not rate_card:
        return None

    property_cols = rate_card.get("property_cols") or []
    composite_key = build_composite_key(values, property_cols)
    row = next((r for r in rate_card.get("rows", []) if r["composite_key"] == composite_key), None)
    quartile = scenario.get("rate_card_quartile") or "p50"
    cost = lookup_cost_from_row(row, quartile)
    return {
        "composite_key": composite_key,
        "cost": cost,
        "quartile": quartile,
        "is_available": bool(row and (row.get("is_available") or row.get("is_manual_override"))),
        "is_manual_override": bool(row.get("is_manual_override")) if row else False,
        "sample_count": row.get("sample_count") if row else 0,
    }

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _to_str(v: Any) -> Optional[str]:
    if v is None:
        return None
    s = str(v)
    if s.lower() in ("nan", "none", ""):
        return None
    return s


def _to_int(v: Any) -> Optional[int]:
    try:
        if v is None or v == "":
            return None
        return int(float(v))
    except (TypeError, ValueError):
        return None


def _to_float(v: Any) -> Optional[float]:
    try:
        if v is None or v == "":
            return None
        f = float(v)
        if f != f:  # NaN
            return None
        return f
    except (TypeError, ValueError):
        return None

